imports:

  # Content example
  - path: github.com/uncinq/lawyerify-example-site-independent
  
  # Theme
  - path: github.com/hugolify/hugolify-theme-3

  # Specific Lawerify
  - path: github.com/uncinq/lawyerify-theme

  # Content
  - path: github.com/hugolify/hugolify-theme-expertises
  - path: github.com/hugolify/hugolify-theme-posts-authors
  - path: github.com/hugolify/hugolify-theme-posts-categories
  - path: github.com/hugolify/hugolify-theme-posts-expertises
  - path: github.com/hugolify/hugolify-theme-posts-tags
  - path: github.com/hugolify/hugolify-theme-posts
  - path: github.com/hugolify/hugolify-theme-persons
  - path: github.com/hugolify/hugolify-theme

  # Core theme
  - path: github.com/hugolify/hugolify-theme

  # CMS
  - path: github.com/hugolify/hugolify-admin
